// Generated by https://quicktype.io

export interface CityWeatherView {
    data:       Data;
    status:     number;
    statusText: string;
    headers:    CityWeatherViewHeaders;
    config:     Config;
    request:    Request;
}

export interface Config {
    transitional:      Transitional;
    adapter:           string[];
    transformRequest:  null[];
    transformResponse: null[];
    timeout:           number;
    xsrfCookieName:    string;
    xsrfHeaderName:    string;
    maxContentLength:  number;
    maxBodyLength:     number;
    env:               Request;
    headers:           ConfigHeaders;
    method:            string;
    url:               string;
}

export interface Request {
}

export interface ConfigHeaders {
    Accept: string;
}

export interface Transitional {
    silentJSONParsing:   boolean;
    forcedJSONParsing:   boolean;
    clarifyTimeoutError: boolean;
}

export interface Data {
    lat:             number;
    lon:             number;
    timezone:        string;
    timezone_offset: number;
    current:         Current;
    currentTime:     number;
    minutely:        Minutely[];
    hourly:          Current[];
    daily:           Daily[];
}

export interface Current {
    dt:             number;
    sunrise?:       number;
    sunset?:        number;
    temp:           number;
    feels_like:     number;
    pressure:       number;
    humidity:       number;
    dew_point:      number;
    uvi:            number;
    clouds:         number;
    visibility:     number;
    wind_speed:     number;
    wind_deg:       number;
    wind_gust:      number;
    weather:        Weather[];
    pop?:           number;
    currentTime:    number;
}

export interface Weather {
    id:          number;
    main:        Main;
    description: Description;
    icon:        string;
}

export enum Description {
    BrokenClouds = "broken clouds",
    ClearSky = "clear sky",
    FewClouds = "few clouds",
    OvercastClouds = "overcast clouds",
    ScatteredClouds = "scattered clouds",
}

export enum Main {
    Clear = "Clear",
    Clouds = "Clouds",
}

export interface Daily {
    dt:         number;
    sunrise:    number;
    sunset:     number;
    moonrise:   number;
    moonset:    number;
    moon_phase: number;
    temp:       Temp;
    feels_like: FeelsLike;
    pressure:   number;
    humidity:   number;
    dew_point:  number;
    wind_speed: number;
    wind_deg:   number;
    wind_gust:  number;
    weather:    Weather[];
    clouds:     number;
    pop:        number;
    uvi:        number;
}

export interface FeelsLike {
    day:   number;
    night: number;
    eve:   number;
    morn:  number;
}

export interface Temp {
    day:   number;
    min:   number;
    max:   number;
    night: number;
    eve:   number;
    morn:  number;
}

export interface Minutely {
    dt:            number;
    precipitation: number;
}

export interface CityWeatherViewHeaders {
    "content-length": string;
    "content-type":   string;
}
